In [1]:
import numpy as np
import os

def get_best_model(task_searches, checkpoint, verbose=True, fewshot_way=None):
    if fewshot_way:
        log_files_a = os.listdir(checkpoint+f"/fewshot_{fewshot_way}way")
    else:
        log_files_a = os.listdir(checkpoint+"/")
    log_files_bs = [[] for _ in range(len(task_searches))]

    for file in log_files_a:
        file_split = file.split(".")
        if(file_split[-1]=="txt"):
            file_split_2 = file_split[0].split("_")
            if file_split_2[0]=="session":
                for idx, task_search in enumerate(task_searches):
                    if file_split_2[1]==str(task_search):
                        log_files_bs[idx].append(file)

    best_acces, best_acc_bes = [], []
    for idx, task_search in enumerate(task_searches):
        best_acc = []
        best_acc_b = []
        for file in log_files_bs[idx]:
            try:
                f = np.loadtxt(checkpoint+"/"+file, skiprows=1)
                best_acc.append(max(f[-1,-1], f[-1,-2]) )
                best_acc_b.append(int(file.split("_")[2]))
            except:
                pass

        bets_acc = np.array(best_acc)
        bets_acc_b = np.array(best_acc_b)

        a = np.argmax(best_acc)
        if verbose:
            print(bets_acc)
            # print(bets_acc_b)
            print(best_acc[a], best_acc_b[a])
        best_acces.append(best_acc[a])
        best_acc_bes.append(best_acc_b[a])

    return best_acces, best_acc_bes

In [10]:
# checkpoint = "../RPSnet-experiments/results/cpin/RPSnet-cls"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-resnet-M8-lr1e-3"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-vit-2-lr1e-4"
checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-vit-MoE-lr0_0005"
# checkpoint = "../RPSnet-experiments/results/cobj/RPSnet-5tasks-lr0_0004"
# checkpoint = "../RPSnet-experiments/results/cobj/RPSnet-vit-lr0_0005"
# checkpoint = "../RPSnet-experiments/results/cobj/RPSnet-vit-MoE-lr1e-05"

'''CGQA'''
sesses = np.arange(0, 10)     # continual train
accs, _ = get_best_model(sesses, checkpoint, verbose=False)
print('get the last one as continual results: ', accs)

sesses = np.arange(10, 110)   # sys
accs_sys, _ = get_best_model(sesses, checkpoint, verbose=False)
print(f'{np.mean(accs_sys):.2f} $\pm$ {1.96 * (np.std(accs_sys)/np.sqrt(len(accs_sys))):.2f}')
sesses = np.arange(310, 410)    # pro
accs_pro, _ = get_best_model(sesses, checkpoint, verbose=False)
print(f'{np.mean(accs_pro):.2f} $\pm$ {1.96 * (np.std(accs_pro)/np.sqrt(len(accs_pro))):.2f}')
sesses = np.arange(610, 710)    # sub
accs_sub, _ = get_best_model(sesses, checkpoint, verbose=False)
print(f'{np.mean(accs_sub):.2f} $\pm$ {1.96 * (np.std(accs_sub)/np.sqrt(len(accs_sub))):.2f}')

Hn = 3/(1/np.mean(accs_sys)+1/np.mean(accs_pro)+1/np.mean(accs_sub))
print(f'Hn={Hn:.2f}')

sesses = np.arange(910, 1010)    # non
accs_non, _ = get_best_model(sesses, checkpoint, verbose=False)
print(f'{np.mean(accs_non):.2f} $\pm$ {1.96 * (np.std(accs_non)/np.sqrt(len(accs_non))):.2f}')
sesses = np.arange(1210, 1310)    # noc
accs_noc, _ = get_best_model(sesses, checkpoint, verbose=False)
print(f'{np.mean(accs_noc):.2f} $\pm$ {1.96 * (np.std(accs_noc)/np.sqrt(len(accs_noc))):.2f}')

Hr = 2/(1/np.mean(accs_non)+1/np.mean(accs_noc))
print(f'Hr={Hr:.2f}')

Ha = 5/(1/np.mean(accs_sys)+1/np.mean(accs_pro)+1/np.mean(accs_sub)+1/np.mean(accs_non)+1/np.mean(accs_noc))
print(f'Ha={Ha:.2f}')

'''COBJ'''
'''10-way 3-task'''
# sesses = np.arange(0, 3)     # single
# accs, _ = get_best_model(sesses, checkpoint, verbose=True)
# print('get the last one as continual results: ', accs)
# sesses = np.arange(3, 103)   # sys cobj     303
# accs_sys, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_sys):.2f} $\pm$ {1.96 * (np.std(accs_sys)/np.sqrt(len(accs_sys))):.2f}')
# sesses = np.arange(303, 403)    # pro cobj      603
# accs_pro, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_pro):.2f} $\pm$ {1.96 * (np.std(accs_pro)/np.sqrt(len(accs_pro))):.2f}')
#
# Hn = 2/(1/np.mean(accs_sys)+1/np.mean(accs_pro))
# print(f'Hn={Hn:.2f}')
#
# sesses = np.arange(903, 1003)    # non cobj     1203
# accs_non, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_non):.2f} $\pm$ {1.96 * (np.std(accs_non)/np.sqrt(len(accs_non))):.2f}')
# sesses = np.arange(1203, 1303)    # noc cobj    1503
# accs_noc, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_noc):.2f} $\pm$ {1.96 * (np.std(accs_noc)/np.sqrt(len(accs_noc))):.2f}')
#
# Hr = 2/(1/np.mean(accs_non)+1/np.mean(accs_noc))
# print(f'Hr={Hr:.2f}')
#
# Ha = 4/(1/np.mean(accs_sys)+1/np.mean(accs_pro)+1/np.mean(accs_non)+1/np.mean(accs_noc))
# print(f'Ha={Ha:.2f}')

'''3-way 10-tasks'''
# sesses = np.arange(0, 9)     # single
# accs, _ = get_best_model(sesses, checkpoint, verbose=True)
# print('get the last one as continual results: ', accs)
# sesses = np.arange(10, 309)   # sys cobj
# accs_sys, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_sys):.2f} $\pm$ {1.96 * (np.std(accs_sys)/np.sqrt(300)):.2f}')
# sesses = np.arange(310, 609)    # pro cobj
# accs_pro, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_pro):.2f} $\pm$ {1.96 * (np.std(accs_pro)/np.sqrt(300)):.2f}')
#
# Hn = 2/(1/np.mean(accs_sys)+1/np.mean(accs_pro))
# print(f'Hn={Hn:.2f}')
#
# sesses = np.arange(910, 1209)    # non cobj
# accs_non, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_non):.2f} $\pm$ {1.96 * (np.std(accs_non)/np.sqrt(300)):.2f}')
# sesses = np.arange(1210, 1509)    # noc cobj
# accs_noc, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_noc):.2f} $\pm$ {1.96 * (np.std(accs_noc)/np.sqrt(300)):.2f}')
#
# Hr = 2/(1/np.mean(accs_non)+1/np.mean(accs_noc))
# print(f'Hr={Hr:.2f}')
#
# Ha = 4/(1/np.mean(accs_sys)+1/np.mean(accs_pro)+1/np.mean(accs_non)+1/np.mean(accs_noc))
# print(f'Ha={Ha:.2f}')

'''6-way 5-tasks'''
# sesses = np.arange(0, 4)     # single
# accs, _ = get_best_model(sesses, checkpoint, verbose=True)
# print('get the last one as continual results: ', accs)
# sesses = np.arange(5, 305)   # sys cobj
# accs_sys, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_sys):.2f} $\pm$ {1.96 * (np.std(accs_sys)/np.sqrt(300)):.2f}')
# sesses = np.arange(305, 605)    # pro cobj
# accs_pro, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_pro):.2f} $\pm$ {1.96 * (np.std(accs_pro)/np.sqrt(300)):.2f}')
#
# Hn = 2/(1/np.mean(accs_sys)+1/np.mean(accs_pro))
# print(f'Hn={Hn:.2f}')
#
# sesses = np.arange(905, 1205)    # non cobj
# accs_non, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_non):.2f} $\pm$ {1.96 * (np.std(accs_non)/np.sqrt(300)):.2f}')
# sesses = np.arange(1205, 1505)    # noc cobj
# accs_noc, _ = get_best_model(sesses, checkpoint, verbose=False)
# print(f'{np.mean(accs_noc):.2f} $\pm$ {1.96 * (np.std(accs_noc)/np.sqrt(300)):.2f}')
#
# Hr = 2/(1/np.mean(accs_non)+1/np.mean(accs_noc))
# print(f'Hr={Hr:.2f}')
#
# Ha = 4/(1/np.mean(accs_sys)+1/np.mean(accs_pro)+1/np.mean(accs_non)+1/np.mean(accs_noc))
# print(f'Ha={Ha:.2f}')


get the last one as continual results:  [10.0, 5.0, 4.333333, 3.475, 4.12, 3.733333, 3.371429, 2.8375, 2.611111, 2.26]


ValueError: attempt to get argmax of an empty sequence

In [5]:
# checkpoint = "../RPSnet-experiments/results/cpin/RPSnet-cls"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-resnet-M8-lr1e-3"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-vit-lr1e-4"

accs = []
for i in range(1,9):
    checkpoint = f"../RPSnet-experiments/results/cifar100/cifar100-t10seed{i}"
    sesses = np.arange(9, 10)     # continual train

    acc, _ = get_best_model(sesses, checkpoint)
    assert len(acc) == 1
    accs.append(acc[-1])

print(accs)
print(f'{np.mean(accs):.2f}% +- {1.96 * (np.std(accs)/np.sqrt(len(accs))):.2f}%')

[34.11 34.26 34.63 34.42 34.29 34.37 34.38 34.24]
34.63 2
[38.52 38.38 38.42 38.51 38.4  38.63 38.34 38.55]
38.63 5
[36.91 36.88 36.91 36.84 36.82 36.92 36.71 36.98]
36.98 7
[34.71 34.64 34.82 34.53 34.78 34.56 34.88 34.88]
34.88 6
[37.65 37.77 37.63 37.69 37.8  37.92 37.9  37.78]
37.92 5
[38.73 38.47 38.82 38.85 38.77 38.59 38.85 39.01]
39.01 7
[36.21 36.08 36.19 36.38 36.24 36.38 36.14 36.1 ]
36.38 3
[38.03 37.75 37.74 37.75 37.73 38.1  37.95 37.79]
38.1 5
[34.63, 38.63, 36.98, 34.88, 37.92, 39.01, 36.38, 38.1]
37.07% +- 1.07%


In [33]:
exp_name = 'RPSnet-vit-lr1e-4'
path = '//172.18.36.77/datasets/RPSnet-experiments/results/cgqa/' + exp_name

for i in range(12):
    data = np.load(path + f'/fixed_path_4_{i}.npy').astype(int)     # fixed_path; path
    print(data)

[[1 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 1 1 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 1]
 [1 0 1 0 0 1 0 0]
 [1 0 0 0 1 1 0 0]
 [1 0 0 0 0 1 0 1]]
[[1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 1 0]
 [1 0 0 0 1 0 0 1]
 [1 0 0 0 0 1 0 0]]
[[1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]
 [1 0 0 1 1 0 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 0 0]]
[[1 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 1]
 [1 1 0 0 0 1 0 0]]
[[1 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 0]
 [1 1 0 0 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 1 0]]
[[1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0