In [2]:
import numpy as np
import os

def get_best_model(task_searches, checkpoint):
    log_files_a = os.listdir(checkpoint+"/")
    log_files_bs = [[] for _ in range(len(task_searches))]

    for file in log_files_a:
        file_split = file.split(".")
        if(file_split[-1]=="txt"):
            file_split_2 = file_split[0].split("_")
            if file_split_2[0]=="session":
                for idx, task_search in enumerate(task_searches):
                    if file_split_2[1]==str(task_search):
                        log_files_bs[idx].append(file)

    best_acces, best_acc_bes = [], []
    for idx, task_search in enumerate(task_searches):
        best_acc = []
        best_acc_b = []
        for file in log_files_bs[idx]:
            try:
                f = np.loadtxt(checkpoint+"/"+file, skiprows=1)
                best_acc.append(max(f[-1,-1], f[-1,-2]) )
                best_acc_b.append(int(file.split("_")[2]))
            except:
                pass

        bets_acc = np.array(best_acc)
        bets_acc_b = np.array(best_acc_b)

        a = np.argmax(best_acc)
        print(bets_acc)
        # print(bets_acc_b)
        print(best_acc[a], best_acc_b[a])
        best_acces.append(best_acc[a])
        best_acc_bes.append(best_acc_b[a])

    return best_acces, best_acc_bes

In [8]:
# checkpoint = "../RPSnet-experiments/results/cpin/RPSnet-cls"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-resnet-M8-lr1e-3"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-vit-2-lr1e-4"
checkpoint = "../RPSnet-experiments/results/cobj/RPSnet-lr0_001"

sesses = np.arange(0, 3)     # single
# sesses = np.arange(9, 10)     # continual train
# sesses = np.arange(10, 310)   # sys
# sesses = np.arange(3, 303)   # sys
# sesses = np.arange(310, 610)    # pro
# sesses = np.arange(303, 603)    # pro
# sesses = np.arange(610, 910)    # sub
# sesses = np.arange(603, 903)    # sub
# sesses = np.arange(910, 1210)    # non
# sesses = np.arange(903, 1203)    # non
# sesses = np.arange(1210, 1510)    # noc
# sesses = np.arange(1203, 1503)    # noc

accs, _ = get_best_model(sesses, checkpoint)

print(accs)
print(f'{np.mean(accs):.2f}% +- {1.96 * (np.std(accs)/np.sqrt(300)):.2f}%')

[50.]
50.0 0
[40.]
40.0 0
[56.]
56.0 0
[49.]
49.0 0
[41.]
41.0 0
[50.]
50.0 0
[45.]
45.0 0
[57.]
57.0 0
[47.]
47.0 0
[49.]
49.0 0
[41.]
41.0 0
[50.]
50.0 0
[53.]
53.0 0
[50.]
50.0 0
[51.]
51.0 0
[42.]
42.0 0
[56.]
56.0 0
[40.]
40.0 0
[57.]
57.0 0
[53.]
53.0 0
[53.]
53.0 0
[39.]
39.0 0
[61.]
61.0 0
[41.]
41.0 0
[41.]
41.0 0
[53.]
53.0 0
[52.]
52.0 0
[50.0, 40.0, 56.0, 49.0, 41.0, 50.0, 45.0, 57.0, 47.0, 49.0, 41.0, 50.0, 53.0, 50.0, 51.0, 42.0, 56.0, 40.0, 57.0, 53.0, 53.0, 39.0, 61.0, 41.0, 41.0, 53.0, 52.0]
48.78% +- 0.70%


In [5]:
# checkpoint = "../RPSnet-experiments/results/cpin/RPSnet-cls"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-resnet-M8-lr1e-3"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-vit-lr1e-4"

accs = []
for i in range(1,9):
    checkpoint = f"../RPSnet-experiments/results/cifar100/cifar100-t10seed{i}"
    sesses = np.arange(9, 10)     # continual train

    acc, _ = get_best_model(sesses, checkpoint)
    assert len(acc) == 1
    accs.append(acc[-1])

print(accs)
print(f'{np.mean(accs):.2f}% +- {1.96 * (np.std(accs)/np.sqrt(len(accs))):.2f}%')

[34.11 34.26 34.63 34.42 34.29 34.37 34.38 34.24]
34.63 2
[38.52 38.38 38.42 38.51 38.4  38.63 38.34 38.55]
38.63 5
[36.91 36.88 36.91 36.84 36.82 36.92 36.71 36.98]
36.98 7
[34.71 34.64 34.82 34.53 34.78 34.56 34.88 34.88]
34.88 6
[37.65 37.77 37.63 37.69 37.8  37.92 37.9  37.78]
37.92 5
[38.73 38.47 38.82 38.85 38.77 38.59 38.85 39.01]
39.01 7
[36.21 36.08 36.19 36.38 36.24 36.38 36.14 36.1 ]
36.38 3
[38.03 37.75 37.74 37.75 37.73 38.1  37.95 37.79]
38.1 5
[34.63, 38.63, 36.98, 34.88, 37.92, 39.01, 36.38, 38.1]
37.07% +- 1.07%


In [33]:
exp_name = 'RPSnet-vit-lr1e-4'
path = '//172.18.36.77/datasets/RPSnet-experiments/results/cgqa/' + exp_name

for i in range(12):
    data = np.load(path + f'/fixed_path_4_{i}.npy').astype(int)     # fixed_path; path
    print(data)

[[1 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 1 1 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 1]
 [1 0 1 0 0 1 0 0]
 [1 0 0 0 1 1 0 0]
 [1 0 0 0 0 1 0 1]]
[[1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 1 0]
 [1 0 0 0 1 0 0 1]
 [1 0 0 0 0 1 0 0]]
[[1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]
 [1 0 0 1 1 0 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 0 0]]
[[1 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 1]
 [1 1 0 0 0 1 0 0]]
[[1 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 0]
 [1 1 0 0 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 1 0]]
[[1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0