In [1]:
import numpy as np
import os

In [28]:

def get_best_model(task_searches, checkpoint):
    log_files_a = os.listdir(checkpoint+"/")
    log_files_bs = [[] for _ in range(len(task_searches))]

    for file in log_files_a:
        file_split = file.split(".")
        if(file_split[-1]=="txt"):
            file_split_2 = file_split[0].split("_")
            if file_split_2[0]=="session":
                for idx, task_search in enumerate(task_searches):
                    if file_split_2[1]==str(task_search):
                        log_files_bs[idx].append(file)

    best_acces, best_acc_bes = [], []
    for idx, task_search in enumerate(task_searches):
        best_acc = []
        best_acc_b = []
        for file in log_files_bs[idx]:
            try:
                f = np.loadtxt(checkpoint+"/"+file, skiprows=1)
                best_acc.append(max(f[-1,-1], f[-1,-2]) )
                best_acc_b.append(int(file.split("_")[2]))
            except:
                pass

        bets_acc = np.array(best_acc)
        bets_acc_b = np.array(best_acc_b)

        a = np.argmax(best_acc)
        print(bets_acc)
        # print(bets_acc_b)
        print(best_acc[a], best_acc_b[a])
        best_acces.append(best_acc[a])
        best_acc_bes.append(best_acc_b[a])

    return best_acces, best_acc_bes

In [29]:
# checkpoint = "../RPSnet-experiments/results/cpin/RPSnet-cls"
# checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-resnet-M8-lr1e-3"
checkpoint = "../RPSnet-experiments/results/cgqa/RPSnet-vit-lr1e-4"

sesses = np.arange(0, 6)     # single
# sesses = np.arange(9, 10)     # continual train
# sesses = np.arange(10, 310)   # sys
# sesses = np.arange(310, 610)    # pro
# sesses = np.arange(610, 910)    # sub
# sesses = np.arange(910, 1210)    # non
# sesses = np.arange(1210, 1510)    # noc

accs, _ = get_best_model(sesses, checkpoint)

print(accs)
print(f'{np.mean(accs):.2f}% +- {1.96 * (np.std(accs)/np.sqrt(300)):.2f}%')

[54.3 54.4 52.2 52.8 54.3 55.5 54.2 53.4]
55.5 5
[39.45 39.   39.55 38.2  39.15 39.55 39.   39.  ]
39.55 2
[22.866667 16.266667 15.066667 21.833333 15.333333 26.366667 16.5
 16.233333]
26.366667 5
[21.95  22.3   22.45  22.925 22.125 22.325 22.15  22.45 ]
22.925 3
[3.14 3.66 2.82 4.16 3.36 4.38 3.92 3.64 4.1  4.46 3.46 4.72]
4.72 9
[6.216667 5.65     5.516667 5.4      3.4      3.1      3.166667 3.133333]
6.216667 0
[55.5, 39.55, 26.366667, 22.925, 4.72, 6.216667]
25.88% +- 2.02%


In [33]:
exp_name = 'RPSnet-vit-lr1e-4'
path = '//172.18.36.77/datasets/RPSnet-experiments/results/cgqa/' + exp_name

for i in range(12):
    data = np.load(path + f'/fixed_path_4_{i}.npy').astype(int)     # fixed_path; path
    print(data)

[[1 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 1 1 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 1]
 [1 0 1 0 0 1 0 0]
 [1 0 0 0 1 1 0 0]
 [1 0 0 0 0 1 0 1]]
[[1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 1 0]
 [1 0 0 0 1 0 0 1]
 [1 0 0 0 0 1 0 0]]
[[1 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]
 [1 0 0 1 1 0 0 0]
 [1 0 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 0 0]]
[[1 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 1]
 [1 1 0 0 0 1 0 0]]
[[1 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 0]
 [1 1 0 0 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 0 0 0 1 1 0]]
[[1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0